# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Download
      env: 
        MGA_TOKEN: ${{ secrets.MGA_TOKEN }}
      run: |
        URL="https://offline-live1.services.u-blox.com/GetOfflineData.ashx?token=${{ secrets.MGA_TOKEN }};gnss=gps"
        cd cmd/mga
        go build ./...
        ./mga  download "https://offline-live1.services.u-blox.com/GetOfflineData.ashx?token=${{ secrets.MGA_TOKEN }};gnss=gps"
        ls -la

    - name: Check if file exists
      run: |
        pwd
        cd cmd/mga
        ls -la
        test mgaoffine.ubx
        test mgaoffine.md5
        cat mgaoffine.md5
        md5sum mgaoffine.ubx
    # - uses: shallwefootball/s3-upload-action@master
    #     with:
    #       aws_key_id: ${{ secrets.AWS_KEY_ID }} 
    #       aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    #       aws_bucket: ${{ secrets.AWS_BUCKET }}
    #       source_dir: 'tmp/'
    #       destination_dir: ${{ github.ref_name }}

    # - name: Build
    #   run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...
